name: Deploy

on:
  push:
    branches:
    - main

  workflow_dispatch:


env:
  AWS_REGION: us-west-2

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4


    - uses: pnpm/action-setup@v2
      name: Install pnpm
      id: pnpm-install
      with:
        version: latest
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
          - args: [--global, aws-cdk]

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3.8.1
      with:
        node-version: 20.x
        check-latest: true
        cache: pnpm

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy
      working-directory: infra
      run: cdk deploy -c env=dev
